version: '3.1'

services:

  db:
    container_name: kdatabase
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Kk1N0ch46
    ports:
      - 5432:5432
    env_file:
      - ".env"
#    network_mode: "host"

  adminer:
    container_name: kadminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
#    network_mode: "host"

  tgbot:
    container_name: kbot
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always
    network_mode: "host"

    env_file:
      - ".env"

